name: check-format

on: 
  workflow_dispatch:
  push: 
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - ".github/workflows/generate-doxygen.yml"
      - ".clang-tidy"

  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - ".github/workflows/generate-doxygen.yml"
      - ".clang-tidy"

jobs:
  check-format:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'
          - 'core'

    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'
          check-path: ${{ matrix.path }}
