name: generate-docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - "doxygen/Doxyfile.in"
      - "doxygen/header.html"
      - ".github/workflows/generate-doxygen.yml"

jobs:
  generate-docs:
    name: "Generate Docs"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Checkout to `main` Branch
        uses: actions/checkout@v4
        with: 
          ref: main
          submodules: true

      - name: Install Required Packages
        run: sudo apt-get update && sudo apt-get install cmake doxygen clang graphviz make -y

      - name: Generate CMake Build Files
        run: cmake -B build

      - name: Generate Documentation
        run: cmake --build build --target doc

      - name: Move `docs` to `github-pages`
        run: mv docs github-pages

      - name: Upload `github-pages` Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: github-pages
  
  deploy-docs:
    name: "Deploy Docs"
    needs: generate-docs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
